#if canImport(AVFoundation) && !os(tvOS)
import Foundation

/// An application-defined stable identifier for one persistable FairPlay key.
public struct HLSFairPlayKeyID: Hashable, Sendable {
    /// The application-owned storage identifier.
    public let rawValue: String

    /// Creates a bounded, nonempty storage identifier.
    ///
    /// Identifiers are limited to 1,024 UTF-8 bytes and cannot contain control
    /// characters. Treat the value as sensitive application data and do not
    /// include it in logs.
    public init(_ rawValue: String) throws {
        let trimmedValue = rawValue.trimmingCharacters(
            in: .whitespacesAndNewlines
        )
        guard
            !trimmedValue.isEmpty,
            rawValue == trimmedValue,
            rawValue.utf8.count <= 1_024,
            !rawValue.unicodeScalars.contains(where: {
                CharacterSet.controlCharacters.contains($0)
            })
        else {
            throw HLSFairPlayPersistentKeyError.invalidKeyIdentifier
        }
        self.rawValue = rawValue
    }
}

/// App-owned inputs needed only when a persistable key is not stored.
public struct HLSFairPlayPersistentKeyAcquisition: Sendable {
    /// The FairPlay application certificate.
    public let applicationCertificate: Data

    /// The opaque content identifier used to create the SPC.
    public let contentIdentifier: Data

    /// FairPlay protocol versions supported by the application's key server.
    ///
    /// Version `1` preserves AVFoundation's default. Advertise newer versions
    /// only after the corresponding KSM and credential set pass Apple's SDK
    /// test vectors. Supply one to 16 unique positive values.
    public let supportedProtocolVersions: [Int]

    /// Whether SPC generation randomizes FairPlay's anonymized device ID.
    ///
    /// The default preserves AVFoundation behavior. Randomized policies require
    /// version 26 or newer and apply only when a stored-key miss creates a new
    /// SPC. Coordinate the policy with the application's KSM first.
    public let deviceIdentifierPolicy: HLSFairPlayDeviceIdentifierPolicy

    /// Creates acquisition inputs for one key request.
    public init(
        applicationCertificate: Data,
        contentIdentifier: Data,
        supportedProtocolVersions: [Int] = [1],
        deviceIdentifierPolicy: HLSFairPlayDeviceIdentifierPolicy =
            .systemDefault
    ) {
        self.applicationCertificate = applicationCertificate
        self.contentIdentifier = contentIdentifier
        self.supportedProtocolVersions = supportedProtocolVersions
        self.deviceIdentifierPolicy = deviceIdentifierPolicy
    }
}

/// A license request delivered to application-owned transport.
public struct HLSFairPlayLicenseRequest: Equatable, Sendable {
    /// The application-defined key identifier.
    public let keyID: HLSFairPlayKeyID

    /// The secure playback context generated by AVFoundation.
    public let spcData: Data

    /// Whether the SPC starts or renews a streaming-key response.
    public let purpose: HLSFairPlayLicenseRequestPurpose

    init(
        keyID: HLSFairPlayKeyID,
        spcData: Data,
        purpose: HLSFairPlayLicenseRequestPurpose = .initial
    ) {
        self.keyID = keyID
        self.spcData = spcData
        self.purpose = purpose
    }
}

/// Application-owned FairPlay license exchange.
public protocol HLSFairPlayLicenseTransporting: Sendable {
    /// Exchanges an SPC for key-vendor response data, commonly called CKC.
    func contentKeyContext(
        for request: HLSFairPlayLicenseRequest
    ) async throws -> Data
}

/// Application-owned persistable FairPlay key storage.
public protocol HLSFairPlayPersistentKeyStoring: Sendable {
    /// Loads a previously stored persistable key.
    func persistableContentKey(
        for keyID: HLSFairPlayKeyID
    ) async throws -> Data?

    /// Atomically stores or replaces one persistable key.
    func storePersistableContentKey(
        _ data: Data,
        for keyID: HLSFairPlayKeyID
    ) async throws
}

/// Hard byte limits for a persistent-key workflow.
public struct HLSFairPlayPersistentKeyLimitPack: Sendable {
    private static let maximumByteLimit = 16 * 1_024 * 1_024

    /// Maximum application-certificate bytes.
    public let maximumApplicationCertificateBytes: Int

    /// Maximum opaque content-identifier bytes.
    public let maximumContentIdentifierBytes: Int

    /// Maximum SPC bytes accepted before license transport.
    public let maximumSPCBytes: Int

    /// Maximum key-vendor response bytes accepted from license transport.
    public let maximumLicenseResponseBytes: Int

    /// Maximum persistable-key bytes loaded from or written to storage.
    public let maximumPersistableKeyBytes: Int

    /// Creates bounded FairPlay material limits.
    ///
    /// Each value is clamped to `1...16 MiB`.
    public init(
        maximumApplicationCertificateBytes: Int =
            1 * 1_024 * 1_024,
        maximumContentIdentifierBytes: Int = 64 * 1_024,
        maximumSPCBytes: Int = 1 * 1_024 * 1_024,
        maximumLicenseResponseBytes: Int = 1 * 1_024 * 1_024,
        maximumPersistableKeyBytes: Int = 1 * 1_024 * 1_024
    ) {
        self.maximumApplicationCertificateBytes = Self.normalized(
            maximumApplicationCertificateBytes
        )
        self.maximumContentIdentifierBytes = Self.normalized(
            maximumContentIdentifierBytes
        )
        self.maximumSPCBytes = Self.normalized(
            maximumSPCBytes
        )
        self.maximumLicenseResponseBytes = Self.normalized(
            maximumLicenseResponseBytes
        )
        self.maximumPersistableKeyBytes = Self.normalized(
            maximumPersistableKeyBytes
        )
    }

    private static func normalized(_ value: Int) -> Int {
        min(maximumByteLimit, max(1, value))
    }
}

/// Configures a persistent-key workflow without owning key material.
public struct HLSFairPlayPersistentKeyConfiguration: Sendable {
    let limits: HLSFairPlayPersistentKeyLimitPack

    private init(
        limits: HLSFairPlayPersistentKeyLimitPack
    ) {
        self.limits = limits
    }

    /// Returns conservative persistent-key defaults.
    public static func safeDefaults()
        -> HLSFairPlayPersistentKeyConfiguration
    {
        advanced()
    }

    /// Returns explicitly tuned persistent-key behavior.
    public static func advanced(
        limits: HLSFairPlayPersistentKeyLimitPack =
            HLSFairPlayPersistentKeyLimitPack()
    ) -> HLSFairPlayPersistentKeyConfiguration {
        HLSFairPlayPersistentKeyConfiguration(limits: limits)
    }
}

/// How a persistable key request was fulfilled.
public enum HLSFairPlayPersistentKeyDisposition: Equatable, Sendable {
    /// Existing app-owned key data fulfilled the request.
    case restored

    /// A license exchange created, stored, and fulfilled a new key.
    case created
}

/// A value-redacted persistent-key workflow failure.
public enum HLSFairPlayPersistentKeyError: Error, Equatable, Sendable {
    /// The application-defined key identifier is unsafe or empty.
    case invalidKeyIdentifier

    /// The application certificate is empty or exceeds its byte limit.
    case invalidApplicationCertificate

    /// The content identifier is empty or exceeds its byte limit.
    case invalidContentIdentifier

    /// The supported FairPlay protocol-version list is empty or malformed.
    case invalidProtocolVersions

    /// Device-ID randomization requires version 26 or newer.
    case deviceIdentifierRandomizationUnavailable

    /// An application-generated device-ID seed was not exactly 16 bytes.
    case invalidDeviceIdentifierSeed

    /// No stored key or online acquisition inputs were available.
    case persistableKeyUnavailable

    /// AVFoundation could not promote the request to a persistable request.
    case persistentRequestRejected

    /// Application-owned storage could not read the key.
    case storageReadFailed

    /// Application-owned storage could not store the key atomically.
    case storageWriteFailed

    /// AVFoundation could not generate a bounded SPC.
    case spcGenerationFailed

    /// Application-owned license transport failed.
    case licenseExchangeFailed

    /// License transport returned empty or oversized response data.
    case invalidLicenseResponse

    /// AVFoundation could not convert the response into a persistable key.
    case persistableKeyCreationFailed

    /// Stored or newly created persistable key data is empty or oversized.
    case invalidPersistableKey
}

extension HLSFairPlayPersistentKeyError: LocalizedError {
    public var errorDescription: String? {
        persistentKeyLocalized(
            "HLSFairPlayPersistentKeyError.\(localizationKey)"
        )
    }

    public var recoverySuggestion: String? {
        persistentKeyLocalized(
            "HLSFairPlayPersistentKeyError.recovery."
                + recoveryLocalizationKey
        )
    }

    private var localizationKey: String {
        switch self {
        case .invalidKeyIdentifier:
            return "invalidKeyIdentifier"
        case .invalidApplicationCertificate:
            return "invalidApplicationCertificate"
        case .invalidContentIdentifier:
            return "invalidContentIdentifier"
        case .invalidProtocolVersions:
            return "invalidProtocolVersions"
        case .deviceIdentifierRandomizationUnavailable:
            return "deviceIdentifierRandomizationUnavailable"
        case .invalidDeviceIdentifierSeed:
            return "invalidDeviceIdentifierSeed"
        case .persistableKeyUnavailable:
            return "persistableKeyUnavailable"
        case .persistentRequestRejected:
            return "persistentRequestRejected"
        case .storageReadFailed:
            return "storageReadFailed"
        case .storageWriteFailed:
            return "storageWriteFailed"
        case .spcGenerationFailed:
            return "spcGenerationFailed"
        case .licenseExchangeFailed:
            return "licenseExchangeFailed"
        case .invalidLicenseResponse:
            return "invalidLicenseResponse"
        case .persistableKeyCreationFailed:
            return "persistableKeyCreationFailed"
        case .invalidPersistableKey:
            return "invalidPersistableKey"
        }
    }

    private var recoveryLocalizationKey: String {
        switch self {
        case .invalidKeyIdentifier:
            return "useOpaqueIdentifier"
        case .invalidApplicationCertificate:
            return "provideCertificate"
        case .invalidContentIdentifier:
            return "provideContentIdentifier"
        case .invalidProtocolVersions:
            return "chooseProtocolVersions"
        case .deviceIdentifierRandomizationUnavailable:
            return "useSupportedDeviceIdentifierPolicy"
        case .invalidDeviceIdentifierSeed:
            return "provideDeviceIdentifierSeed"
        case .persistableKeyUnavailable:
            return "provideAcquisition"
        case .persistentRequestRejected:
            return "handlePersistableDelegate"
        case .storageReadFailed, .storageWriteFailed:
            return "checkStorage"
        case .spcGenerationFailed:
            return "checkFairPlayInputs"
        case .licenseExchangeFailed, .invalidLicenseResponse:
            return "checkLicenseTransport"
        case .persistableKeyCreationFailed, .invalidPersistableKey:
            return "requestNewKey"
        }
    }
}

@inline(__always)
private func persistentKeyLocalized(_ key: String) -> String {
    NSLocalizedString(
        key,
        bundle: .module,
        comment: "AVFoundation HLS persistent FairPlay key diagnostic"
    )
}
#endif
